### ISSUE TITLE
Compiling rust-peer to wasm

### ISSUE THREAD

**Issue by Larkooo** [libp2p/universal-connectivity#108]
Would be cool if rust-peer could support compiling to wasm directly with wasm-pack (it currently fails) and exporting it as a node package or using it in the browser

**Comment by thomaseizinger** [comment]
The current Rust node is designed as a bootstrapper and needs to listen on network interfaces. That is not possible in the browser.

We support WebTransport, WebRTC and WebSocket as transports in WASM but the usecases are different.

You could build a 2nd Rust peer that replicates what the JS peer does but compiling the current one to WASM doesn't really make sense to me.
