### ISSUE TITLE
Unable to start the js node

### ISSUE THREAD

**Issue by emiamar** [libp2p/universal-connectivity#198]
Facing this error.
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/21c802d3-505e-4b86-8352-23c584fca3f7">

When I am commenting, https://github.com/libp2p/universal-connectivity/blob/main/js-peer/src/lib/libp2p.ts#L64 line it start up. However with no connections.
<img width="1504" alt="image" src="https://github.com/user-attachments/assets/4afc6673-fe43-47f2-b8cb-10dcd6d9eabc">

I also have go node running on public internet and not able to connect to it. It complains no valid address
![image](https://github.com/user-attachments/assets/9c2cbff1-7cbe-435f-b1f7-f3d43770c0af)

**Comment by tabcat** [comment]
The quic transport is not supported by the js-peer. There is a [table on the readme](https://github.com/libp2p/universal-connectivity?tab=readme-ov-file#packages) which shows what transports each implementation supports.

js-peers can connect with go-peers via webtransport. A webtransport multiaddr will look like [this](https://github.com/libp2p/universal-connectivity?tab=readme-ov-file#using-a-multiaddr).

**Comment by 2color** [comment]
As @tabcat, QUIC isn't available in browsers. Supported transports for the js browser peer can be found here:

https://github.com/libp2p/universal-connectivity/blob/7f7a54cd7340b8ef8b5a98b92e4794735d788d55/js-peer/src/lib/libp2p.ts#L50-L54
