### ISSUE TITLE
Render indenticons for peers in chat 

### ISSUE THREAD

**Issue by 2color** [libp2p/universal-connectivity#20]
## Background

Once multiple peers join a chat room, the UI should help you distinguish who the messages are coming from. 

[Identicons](https://en.wikipedia.org/wiki/Identicon) are a common way to do create unique visual identifiers.

## Details

Render an identicon next to each message in the chat UI based on the peer ID. 

Note that this requires that all messages are signed; otherwise, the originating peer ID is not included in the message.

**Comment by p-shahi** [comment]
done by @jochasinga in #14
