### ISSUE TITLE
Go Node Tasks

### ISSUE THREAD

**Issue by TheDiscordian** [libp2p/universal-connectivity#23]
Noting these down to help track them:

- [x] Should be able to connect to a list of multiaddrs via cli flag
- [x] QUIC / TCP / WebSocket transports
- [x] public EC2 ip address via a cli flag using Address Factory

**Comment by p-shahi** [comment]
We also need to be able to add the public EC2 ip address via a cli flag using Address Factory

**Comment by MarcoPolo** [comment]
Wold be cool to get webtransport in as well :)

**Comment by TheDiscordian** [comment]
@MarcoPolo WebTransport is already supported :)
