### ISSUE TITLE
Improvements to the Go daemon

### ISSUE THREAD

**Issue by 2color** [libp2p/universal-connectivity#5]
From our testing, we can confirm that the Go chat daemon can exchange messages with the frontend.

To make it more suitable for deployment and cleaner, we need to make the following changes:
- [ ] Enable a persistent PeerID, either via an env var or serialised as a file. This is to ensure that the PeerId doesn't change on every reload. We need this because we will hard code at least one PeerID into the frontend to make sure "it just works" on load. 
- [ ] Instead of logging every system logs into the chat window, create a split view for the system logs
- [ ] Publish messages directly without json

**Comment by TheDiscordian** [comment]
1. Going to keep PeerID via this: https://github.com/TheDiscordian/go-libp2p-relay-daemon/blob/master/identity.go#L10
2. Will either do a split view or to file (attempting split view first)
3. 👍
