### ISSUE TITLE
Set sane limits for the browser node

### ISSUE THREAD

**Issue by p-shahi** [libp2p/universal-connectivity#60]
The current limits set in libp2p.ts were set at their current values in order to get the app working for the IPFS Thing demo.
We need to configure saner limits instead of these arbitrarily high values.

Limits to address
```
    dht: kadDHT({
      protocolPrefix: "/universal-connectivity",
      maxInboundStreams: 5000,
      maxOutboundStreams: 5000,
      clientMode: true
    }),
``` 
https://github.com/libp2p/universal-connectivity/blob/main/packages/frontend/src/lib/libp2p.ts#L32

```
    identify: {
      // these are set because we were seeing a lot of identify and identify push
      // stream limits being hit
      maxPushOutgoingStreams: 1000,
      maxPushIncomingStreams: 1000,
      maxInboundStreams: 1000,
      maxOutboundStreams: 1000,
    },
```
https://github.com/libp2p/universal-connectivity/blob/main/packages/frontend/src/lib/libp2p.ts#L70

Documented more in https://hackmd.io/K_MkPfjOTyaLfLME4b25aw

**Comment by 2color** [comment]
I believe this can be closed as the connection limits are set using the libp2p connection manager:

https://github.com/libp2p/universal-connectivity/blob/022b5a9f620662e98cc0ae937ed4b80cc9c28dd6/js-peer/src/lib/libp2p.ts#L73-L76
