### ISSUE TITLE
Display browser nodes listen addresses in UI

### ISSUE THREAD

**Issue by p-shahi** [libp2p/universal-connectivity#65]
We currently only display the peer ID, but we should also display a browser nodes listen addresses (i.e. it's webrtc-direct, websocket, relayed multiaddr)
This will be informative and also aid in debugging (currently, we have to grab the listen addresses from the console log)

**Comment by p-shahi** [comment]
@maschad this is fairly small would you be able to take this on?

**Comment by maschad** [comment]
sure @p-shahi
