### ISSUE TITLE
Support sending files 

### ISSUE THREAD

**Issue by youngjoon-lee** [libp2p/universal-connectivity#69]
Hi all,

Thank you for making this repo. It’s super helpful to understand how to configure nodes for each programming languages and to see the current state of libp2p connectivity. 

If I’m allowed, I would like to try to implement the file-sharing feature using the request-response protocol. The file-sharing example is already presented in the rust-libp2p repo, but it would be meaningful to implement it in this repo using multiple programming languages. 

I’m thinking about the following scenario. 
- Browser A clicks a send-file button next to the message textbox. Then, a file browser is opened. The user selects a file. The browser holds the file in memory and provide the file using Kademlia (start-providing). Plus, Browser A publishes a special message `FileAd(name)` via gossipsub. 
- Other browser peers, which receive the `FileAd(name)` message, execute the Kademlia get-provider operation. After getting the provider information, it sends a file request to Browser A by its relay address. Until the file is delivered, web UI just shows a temporary message box: `Receiving a file`. 
- Finally, Browser A sends a file response back to the file requester. Then, the web UI of the file requester displays a clickable file name in the message box, so that the user can download the file to their local. 

I’m not sure if this scenario will work, but I think it’s worth trying, if I can have a chance to do it.

**Comment by youngjoon-lee** [comment]
> @youngjoon-lee That would awesome, and a very useful feature for a chat app such as this. If you would like to do this, please feel free to! I had some idea about this myself about perhaps integrating with https://github.com/ipfs/helia as a backend for storing files

Thank you! I'll share a draft PR with you soon!

**Comment by mxinden** [comment]
> Browser A clicks a send-file button next to the message textbox. Then, a file browser is opened. The user selects a file. The browser holds the file in memory and provide the file using Kademlia (start-providing). Plus, Browser A publishes a special message `FileAd(name)` via gossipsub.

For the sake of simplicity, given that you are already planning to publish to a gossipsub topic, you might as well include the nodes addresses in the announcement, thus alleviating the need for Kademlia and its Provider system.

**Comment by youngjoon-lee** [comment]
> For the sake of simplicity, given that you are already planning to publish to a gossipsub topic, you might as well include the nodes addresses in the announcement, thus alleviating the need for Kademlia and its Provider system.

Thank you! That’s more efficient 👍

**Comment by youngjoon-lee** [comment]
> For the sake of simplicity, given that you are already planning to publish to a gossipsub topic, you might as well include the nodes addresses in the announcement, thus alleviating the need for Kademlia and its Provider system.

Thank you! That’s definitely more efficient. 👍 

I have a short question. It seems that the request-response protocol is implemented only in rust-libp2p, not in js-libp2p and go-libp2p. Is the request-response not a part of the official libp2p spec? or is it a deprecated spec? If so, I need to consider using IPFS as @p-shahi suggested above, but I’m not sure if it’s okay to use IPFS in this repo, considering the coverage/purpose of this universal-connectivity topic

**Comment by p-shahi** [comment]
@youngjoon-lee request/response or libp2p + HTTP is an active area of development right now. There is a spec being written: https://github.com/libp2p/specs/pull/508 and some draft PRs in go-libp2p right now. In js-libp2p we have this prototype: https://github.com/MarcoPolo/js-libp2p-fetch
Adding this is a high priority for the team atm, so please stay tuned!

Wrt integrating with Helia in this repo: You're right, the goal of this project is to showcase different libp2p transports/connectivity capabilities all in one application. We'll be creating a tutorial that shows how to build it etc: https://github.com/libp2p/universal-connectivity/issues/67

I think adding a Helia integration would be cool, but maybe in a forked repo?
One of our goals after finishing up this app was to create a guide on fetching a CID with Helia using the libp2p peers.
Depending on how your organize the new integration in the codebase, I think there's a case for the fork to be merged in here too

**Comment by BigLep** [comment]
As far as an example that uses IPFS in a browser to share files, I'm just passing on that there is https://github.com/ipfs-shipyard/ipfs-share-files and there is an issue (https://github.com/ipfs-shipyard/ipfs-share-files/issues/136 ) to move it to Helia.  I'm just passing that on as an FYI.

**Comment by thomaseizinger** [comment]
> > For the sake of simplicity, given that you are already planning to publish to a gossipsub topic, you might as well include the nodes addresses in the announcement, thus alleviating the need for Kademlia and its Provider system.
> 
> Thank you! That’s definitely more efficient. 👍 
> 
> I have a short question. It seems that the request-response protocol is implemented only in rust-libp2p, not in js-libp2p and go-libp2p.

The `request-response` module is just an abstraction to send a request and receive a response on a stream. You can do this in all other languages too! Just use the same codec.

For example, soon, there will be out-of-the-box JSON and CBOR support: https://github.com/libp2p/rust-libp2p/pull/3952

The only convention that you need to follow in other languages is to close the stream after writing (both for requests and responses).

**Comment by p-shahi** [comment]
@youngjoon-lee Btw if you're interested in working on this, I think this would be a good project for HackFS our upcoming hackathon: https://ethglobal.com/events/hackfs2023
Would love it you join (registration ends 11:59pm ET)

**Comment by youngjoon-lee** [comment]
> @youngjoon-lee Btw if you're interested in working on this, I think this would be a good project for HackFS our upcoming hackathon: https://ethglobal.com/events/hackfs2023
> Would love it you join (registration ends 11:59pm ET)

Thank you! I will
