### ISSUE TITLE
Upgrade to js-libp2p 0.45.0

### ISSUE THREAD

**Issue by p-shahi** [libp2p/universal-connectivity#71]

**Comment by p-shahi** [comment]
@maschad I think Alex already has done this but has yet to push his changes

**Comment by achingbrain** [comment]
I do, everything's ready do go but it's currently blocked by https://github.com/ChainSafe/js-libp2p-gossipsub/pull/425

**Comment by achingbrain** [comment]
Now just needs https://github.com/ChainSafe/js-libp2p-gossipsub/pull/428
