### ISSUE TITLE
Example using circuit relay

### ISSUE THREAD

**Issue by eugenechyrski** [libp2p/universal-connectivity#72]
Will it work with circuit relay servers? can you provide an example for that?

**Comment by maschad** [comment]
Hey @eugenechyrski it currently does, in this example the [rust peer](https://github.com/libp2p/universal-connectivity/blob/main/rust-peer/src/main.rs#L314-L324) acts a relay server for two browsers to connect over our [circuitRelayTransport](https://github.com/libp2p/universal-connectivity/blob/main/packages/frontend/src/lib/libp2p.ts#L49-L51)
