### ISSUE TITLE
Create a CODEOWNERS file

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/universal-connectivity#80]
We should create a CODEOWNERS file for the individual directories of the different languages. That way, the various teams will automatically be requested a review for when [dependabot](https://github.com/libp2p/universal-connectivity/issues/79) opens a new PR.

**Comment by thomaseizinger** [comment]
I'd suggest we use @libp2p/rust-libp2p-maintainers, @libp2p/go-libp2p-maintainers and @libp2p/js-libp2p-chainsafe-maintainers so any of the team members can "claim" a PR.

**Comment by 2color** [comment]
Closing as it's done
