### ISSUE TITLE
JS: use js-libp2p-logger instead of `console.log`

### ISSUE THREAD

**Issue by youngjoon-lee** [libp2p/universal-connectivity#82]
As discussed [here](https://github.com/libp2p/universal-connectivity/pull/76#discussion_r1272671243), it would be better to use [js-libp2p-logger](https://github.com/libp2p/js-libp2p-logger) than `console.log`.

I'd like to assign this issue to myself.

**Comment by 2color** [comment]
Closed by https://github.com/libp2p/universal-connectivity/pull/144
